import { MotionType } from '../src/motion'
import Vim from '../src/vim'

describe('Vim motion commands', () => {
    const make_vim = (t) => new Vim(t)
    const make_motion_cmd = (t: string, count?: number) => ({ type: <MotionType>t, count })
    const right = make_motion_cmd('l')
    const left = make_motion_cmd('h')
    const up = make_motion_cmd('k')
    const down = make_motion_cmd('j')
    test('normal mode left-right', () => {
        const v = make_vim('hello world')
        v.execute_command(right)
        expect(v.cursor).toEqual(1)
        v.execute_command(left)
        expect(v.cursor).toEqual(0)
        v.execute_command(left)
        expect(v.cursor).toEqual(0)
        v.execute_command(up)
        expect(v.cursor).toEqual(0)
        v.execute_command(down)
        expect(v.cursor).toEqual(0)
    })
    test('normal mode up-down', () => {
        const v = make_vim('hello\nworld')
        v.execute_command(down)
        expect(v.cursor).toEqual(6)
        v.execute_command(up)
        expect(v.cursor).toEqual(0)
        v.execute_command(right)
        v.execute_command(down)
        expect(v.cursor).toEqual(7)
    })
    test('normal mode blank line', () => {
        const v = make_vim('ab\n\ncd')
        v.execute_command(right)
        v.execute_command(down)
        expect(v.cursor).toEqual(3)
        v.execute_command(down)
        expect(v.cursor).toEqual(5)
    })
})
